name = "Modpack Misterio"
author = "Misterio <eu@misterio.me>"
version = "0.2.17"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "101aa014a99e15124c6b28099514e5fc72b202c248c5807e732e86ee1f784ffe"

[versions]
fabric = "0.14.21"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
