name = "Modpack Misterio"
author = "Misterio <eu@misterio.me>"
version = "0.2.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7100edde27574f33adf79998d7883401a570a62768aa0fb9a69c7862ffe0a82"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
