name = "Modpack Misterio"
author = "Misterio <eu@misterio.me>"
version = "0.2.17"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a831b9dbad5fc56c6935373416b24f4689c2dd23bbd566eb1ebe1c3b368f36f8"

[versions]
fabric = "0.14.21"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
